"""
docs.conf
=========

Sphinx conf for setup docs
"""
# pylint: disable=C0103,W0622

# # -- Options for HTML output -----------------------------------------
# -- Project information -----------------------------------------------
project = "pyaud"
author = "Stephen Whitlock"
email = "stephen@jshwisolutions.com"
maintainer = "Stephen Whitlock"
maintainer_email = "stephen@jshwisolutions.com"
# noinspection PyShadowingBuiltins
license = "MIT"
release = "1.0.0"
# noinspection PyShadowingBuiltins
copyright = "2021, Stephen Whitlock"
# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
    "sphinx.ext.autodoc",
    "sphinx.ext.imgmath",
    "sphinx.ext.doctest",
    "sphinxcontrib.programoutput",
    "sphinx.ext.githubpages",
    "sphinxcontrib.fulltoc",
]


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to
# documentation for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "monokai"

# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages. See the documentation
# for a list of builtin themes.
#

# Theme options are theme-specific and customize the look and feel of a
# theme further. For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets)
# here, relative to this directory. They are copied after the builtin
# static files, so a file named "default.css" will overwrite the builtin
# "default.css".

# Custom sidebar templates, must be a dictionary that maps document
# names to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}
# ---sphinx-themes-----
html_theme = "graphite"
html_domain_indices = True
html_use_index = True
html_show_sourcelink = True
html_show_sphinx = False
html_theme_path = ["_themes"]
html_sidebars = {"**": ["globaltoc.html", "searchbox.html"]}

todo_include_todos = True
autoclass_content = "both"
autodoc_member_order = "bysource"
autodoc_default_options = {"members": None}
logo = "_static/icon.png"
add_function_parentheses = True
add_module_names = True
