name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GH_NAME: jshwi
      GH_EMAIL: stephen@jshwisolutions.com
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODECOV_SLUG: jshwi/pyaud

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update Apt
      run: sudo apt-get install zstd -y

    - name: Install Pipenv
      run: python -m pip install --upgrade pip pipenv wheel

    - uses: actions/cache@v2
      id: pipenv-cache
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: ${{ runner.os }}-pipenv-

    - name: Setup Pip
      if: steps.pipenv-cache.outputs.cache-hit != 'true'
      run: pipenv install --dev

    - name: Audit
      run: pipenv run pyaud audit --deploy
