name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GH_NAME: jshwi
      GH_EMAIL: stephen@jshwisolutions.com
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODECOV_SLUG: jshwi/pyaud

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update Apt
      run: sudo apt-get install zstd -y

    - uses: actions/cache@v2
      id: cachepip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Setup Pip
      run: python -m pip install --upgrade pip wheel
      if: steps.cachepip.outputs.cache-hit != 'true'

    - name: Install PyAud
      run: pip install .

    - name: Audit
      run: pyaud audit --deploy
