name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    env:
      PYAUD_GH_NAME: jshwi
      PYAUD_GH_EMAIL: stephen@jshwisolutions.com
      PYAUD_GH_TOKEN: ${{ secrets.PYAUD_GH_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODECOV_SLUG: jshwi/pyaud

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout build
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install zstd
      run: |
        sudo apt-get update
        sudo apt-get install zstd -y

    - name: Install Pipenv
      run: python -m pip install --upgrade pip pipenv wheel

    - name: Cache Virtualenvs
      uses: actions/cache@v2
      id: pipenv-cache
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Pipfile.lock') }}

    - name: Setup Virtualenv
      if: steps.pipenv-cache.outputs.cache-hit != 'true'
      run: pipenv install --dev

    - name: Audit
      run: |
        python -m pipenv run pip install -e .
        python -m pipenv run pyaud audit --deploy --rcfile .github/pyaud.toml
