name: ci

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  ci:
    name: ${{ matrix.os }}-python${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    env:
      PYAUD_GH_NAME: jshwi
      PYAUD_GH_EMAIL: stephen@jshwisolutions.com
      PYAUD_GH_TOKEN: ${{ secrets.PYAUD_GH_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODECOV_SLUG: jshwi/pyaud

    strategy:
      matrix:
        # this works like a loop; think `pytest.mark.parametrize`
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
      - name: Checkout build
        id: checkout-build
        uses: actions/checkout@v2

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        id: install-poetry
        run: |
          pip install --upgrade pip poetry

      - name: Cache Poetry
        uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/poetry.lock') }}

      - name: Restore cache
        id: restore-cache
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Audit
        id: audit
        run: |
          poetry run pyaud audit --deploy --rcfile .github/pyaud.toml
